on: [push, workflow_dispatch]

name: Coverage

jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin --all --line --out Stdout --fail-under 80

